version: "2"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: teracy/dev:dev_develop
    command: bash -c "rake build && rake berks_install"
    volumes:
      - .:/opt/app
